import "./styles/globals.scss";
import type { Metadata } from "next";
import Container from "./patterns/Container";
import Content from "./patterns/Content";
import Aside from "./patterns/Aside";
import Menu from "./patterns/Menu";
import Header from "./patterns/Header";

export const metadata: Metadata = {
  title: "Taher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <Container>
          <Aside />
          <Menu />
          <Header />
          <Content>{children}</Content>
        </Container>
      </body>
    </html>
  );
}
